export const provincias = [
  { nombre: "Todas las provincias", municipios: [] },
  {
    nombre: "Pinar del Río",
    municipios: [
      "Pinar del Río",
      "Consolación del Sur",
      "Guane",
      "San Juan y Martínez",
      "Los Palacios",
      "Mantua",
      "Minas de Matahambre",
      "La Palma",
      "San Luis",
      "Sandino",
      "Viñales",
    ],
  },
  {
    nombre: "Artemisa",
    municipios: [
      "Artemisa",
      "Bauta",
      "Caimito",
      "Guanajay",
      "Güira de Melena",
      "Mariel",
      "San Antonio de los Baños",
      "Bahía Honda",
      "Candelaria",
      "San Cristóbal",
      "Alquízar",
    ],
  },
  {
    nombre: "La Habana",
    municipios: [
      "Arroyo Naranjo",
      "Boyeros",
      "Centro Habana",
      "Cerro",
      "Cotorro",
      "Diez de Octubre",
      "Guanabacoa",
      "La Habana del Este",
      "La Habana Vieja",
      "Marianao",
      "Playa",
      "Plaza de la Revolución",
      "Regla",
      "San Miguel del Padrón",
      "Habana del Oeste",
    ],
  },
  {
    nombre: "Mayabeque",
    municipios: [
      "San José de las Lajas",
      "Batabanó",
      "Jaruco",
      "Santa Cruz del Norte",
      "Melena del Sur",
      "Nueva Paz",
      "Quivicán",
      "San Nicolás de Bari",
      "Güines",
      "Madruga",
      "Bejucal",
    ],
  },
  {
    nombre: "Matanzas",
    municipios: [
      "Matanzas",
      "Cárdenas",
      "Colón",
      "Jagüey Grande",
      "Jovellanos",
      "Limonar",
      "Los Arabos",
      "Martí",
      "Pedro Betancourt",
      "Perico",
      "Unión de Reyes",
      "Calimete",
      "Ciénaga de Zapata",
    ],
  },
  {
    nombre: "Cienfuegos",
    municipios: [
      "Cienfuegos",
      "Abreus",
      "Cruces",
      "Cumanayagua",
      "Palmira",
      "Rodas",
      "Lajas",
      "Rodríguez",
    ],
  },
  {
    nombre: "Villa Clara",
    municipios: [
      "Santa Clara",
      "Camajuaní",
      "Caibarién",
      "Cifuentes",
      "Corralillo",
      "Encrucijada",
      "Manicaragua",
      "Placetas",
      "Quemado de Güines",
      "Ranchuelo",
      "Remedios",
      "Sagua la Grande",
      "Santo Domingo",
    ],
  },
  {
    nombre: "Sancti Spíritus",
    municipios: [
      "Sancti Spíritus",
      "Cabaiguán",
      "Fomento",
      "Jatibonico",
      "La Sierpe",
      "Taguasco",
      "Trinidad",
      "Yaguajay",
    ],
  },
  {
    nombre: "Ciego de Ávila",
    municipios: [
      "Ciego de Ávila",
      "Baraguá",
      "Bolivia",
      "Chambas",
      "Ciro Redondo",
      "Florencia",
      "Majagua",
      "Morón",
      "Primero de Enero",
      "Venezuela",
    ],
  },
  {
    nombre: "Camagüey",
    municipios: [
      "Camagüey",
      "Carlos Manuel de Céspedes",
      "Esmeralda",
      "Florida",
      "Guáimaro",
      "Jimaguayú",
      "Minas",
      "Najasa",
      "Nuevitas",
      "Santa Cruz del Sur",
      "Sibanicú",
      "Sierra de Cubitas",
      "Vertientes",
    ],
  },
  {
    nombre: "Las Tunas",
    municipios: [
      "Las Tunas",
      "Amancio Rodríguez",
      "Colombia",
      "Jesús Menéndez",
      "Jobabo",
      "Majibacoa",
      "Manatí",
      "Puerto Padre",
    ],
  },
  {
    nombre: "Holguín",
    municipios: [
      "Holguín",
      "Antilla",
      "Báguanos",
      "Banes",
      "Cacocum",
      "Calixto García",
      "Cueto",
      "Frank País",
      "Gibara",
      "Mayarí",
      "Moa",
      "Rafael Freyre",
      "Sagua de Tánamo",
      "Urbano Noris",
    ],
  },
  {
    nombre: "Santiago de Cuba",
    municipios: [
      "Santiago de Cuba",
      "Contramaestre",
      "Guamá",
      "Mella",
      "Palma Soriano",
      "San Luis",
      "Segundo Frente",
      "Songo-La Maya",
      "Tercer Frente",
    ],
  },
  {
    nombre: "Granma",
    municipios: [
      "Bayamo",
      "Bartolomé Masó",
      "Buey Arriba",
      "Campechuela",
      "Cauto Cristo",
      "Guisa",
      "Jiguaní",
      "Manzanillo",
      "Media Luna",
      "Niquero",
      "Pilón",
      "Río Cauto",
      "Yara",
    ],
  },
  {
    nombre: "Guantánamo",
    municipios: [
      "Guantánamo",
      "Baracoa",
      "Caimanera",
      "El Salvador",
      "Imías",
      "Maisí",
      "Manuel Tames",
      "Niceto Pérez",
      "San Antonio del Sur",
      "Yateras",
    ],
  },
];
