import { Providers } from "./providers";
import "./globals.css";
import type { Metadata } from "next";
import NavigationBar from "@/components/navbar/NavigationBar";

import { Suspense } from "react";
import Loading from "./loading";
import FilterModal from "@/components/modal/FilterModal";
export const metadata: Metadata = {
  title: "Marketplace",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavigationBar />   
          <Suspense fallback={<Loading />}>
            <div className="mt-0 mx-2">
            {children}
            <FilterModal/>
            </div>
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
