
import { Providers } from "./providers";
import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import NavigationBar from "@/components/navbar/NavigationBar"
import App from "@/components/drop/Drop";

const open = Open_Sans({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Marketplace",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  
  children: React.ReactNode;
}) 
{



  return (
    <html lang="en">
      <body>
        <Providers>
        <NavigationBar/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
